export declare enum SubscriptionEvent {
    PICK_JOB_CREATED = "PICK_JOB_CREATED",
    PICK_JOB_PICKING_FINISHED = "PICK_JOB_PICKING_FINISHED",
    PICK_JOB_ABORTED = "PICK_JOB_ABORTED",
    HANDOVERJOB_HANDED_OVER = "HANDOVERJOB_HANDED_OVER"
}
